In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.6,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.6 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [5]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[61 82 68 58 96 67]


In [6]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.60825548 0.56757691 0.38182935 0.9989003  0.61379913 0.22328113]


In [7]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.60825548 2.56757691 2.38182935 2.9989003  2.61379913 2.22328113]


In [8]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[183 246 204 174 288 201]


In [14]:
feature = np.random.randint(low= 6, high=21, size=(15))
print(feature)

[14 17  6 18 14  6 13 18 14  8 20 12 18  8 10]


In [24]:
lable = feature*3+4
print(lable)

[46 55 22 58 46 22 43 58 46 28 64 40 58 28 34]


In [25]:
noise = lable + np.random.random([15])*2
print(noise)
print(lable)

[46.23461573 56.14331449 22.77573188 58.6013051  46.60115134 22.87941793
 44.72026471 58.78295973 47.3579742  29.40257118 65.15373723 40.35854213
 58.65185489 28.20898122 35.35254223]
[46 55 22 58 46 22 43 58 46 28 64 40 58 28 34]


In [29]:
noise = (np.random.random([15]) * 4)-2
print(noise)
lable = lable + noise 
print(lable)

[3.69811464 0.33620824 2.08319608 0.96834413 1.44298181 3.95547711
 1.46655157 0.64864189 2.62337618 1.8977362  1.73271063 0.63756163
 3.77567623 2.94326249 1.07405289]
[51.04885275 56.29541861 26.05524451 59.80123912 47.97578072 26.79797704
 42.67563013 57.11756888 49.24898937 28.60656115 65.83467661 38.72957918
 60.95459182 32.00864755 33.98824595]


In [31]:
import pandas as pd

In [32]:
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

In [33]:
my_column_names = ['temperature', 'activity']

In [34]:
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [35]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

In [36]:
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [37]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [38]:
print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

Row #2:
   temperature  activity  adjusted
2           20         9        11 



In [39]:
print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 



In [40]:
print("Column 'temperature':")
print(my_dataframe['temperature'])

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


In [57]:
my_data1=np.random.randint(low=0, high=101, size=(3,4))
my_column_names1 = ['Eleanor', 'Chidi','Tahani','Jason']
my_dataframe1 = pd.DataFrame(data=my_data1, columns=my_column_names1)
print(my_dataframe1)
print("\n")
print(my_dataframe1['Eleanor'][1])


   Eleanor  Chidi  Tahani  Jason
0       77     23      55     73
1       41     42      71     39
2       65      3       3     36


41


In [60]:
my_dataframe1["Janet"]= my_dataframe1["Tahani"] + my_dataframe1["Jason"]
print(my_dataframe1)

   Eleanor  Chidi  Tahani  Jason  Janet
0       77     23      55     73    128
1       41     42      71     39    110
2       65      3       3     36     39


In [61]:
reference_to_df = my_dataframe1

In [62]:
print("  Starting value of df: %d" % my_dataframe1['Jason'][1])

  Starting value of df: 39


In [63]:
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

  Starting value of reference_to_df: 39



In [65]:
my_dataframe1.at[1, 'Jason'] = my_dataframe1['Jason'][1] + 5

In [66]:
print("  Updated df: %d" % my_dataframe1['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

  Updated df: 44
  Updated reference_to_df: 44




In [67]:
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

Experiment with a true copy:


In [68]:
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])


  Starting value of my_dataframe: 7
  Starting value of copy_of_my_dataframe: 7



In [69]:
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

  Updated my_dataframe: 10
  copy_of_my_dataframe does not get updated: 7
